publicaciones:
    resource: "@PublicacionesBundle/Controller/"
    type:     annotation
    prefix:   /

categorias_galeria:
    resource: "@CategoriasGaleriaBundle/Controller/"
    type:     annotation
    prefix:   /

richpolis_backend:
    resource: "@BackendBundle/Controller/"
    type:     annotation
    prefix:   /backend

richpolis_frontend:
    resource: "@FrontendBundle/Controller/"
    type:     annotation
    prefix:   /

_imagine:
    resource: .
    type:     imagine
