<?php

namespace Richpolis\FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TracksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TracksRepository extends EntityRepository
{
    public function getMaxPosicion($disco=0){
        $em=$this->getEntityManager();
        if($disco==0){
        $query=$em->createQuery('
            SELECT MAX(t.posicion) as value 
            FROM FrontendBundle:Tracks t 
            ORDER BY t.posicion ASC
            ');
        }else{
        $query=$em->createQuery('
            SELECT MAX(t.posicion) as value 
            FROM FrontendBundle:Tracks t 
            WHERE t.disco=:disco 
            ORDER BY t.posicion ASC
            ')->setParameter('disco', $disco);
        }
        $query->setMaxResults(1);
        $max=$query->getResult();
        return $max[0]['value'];
    }
    
    
    public function getQueryTracksActivas($todas=false){
		$query=$this->createQueryBuilder('t')
                    ->orderBy('t.disco', 'ASC')
                    ->addOrderBy('t.posicion','ASC');
        if(!$todas){
            $query->andWhere('t.isActive=:active')
                  ->setParameter('active', true);
        }

        return $query->getQuery();
    }
    
    public function getTracksActivas($todas=false){
        $query=$this->getQueryTracksActivas($todas);
        return $query->getResult();
    }
    
    public function getQueryTracksPorDiscoActivas($disco,$todas=false){
		$query=$this->createQueryBuilder('t')
                    ->where('t.disco=:disco')
                    ->setParameter('disco', $disco)
                    ->addOrderBy('t.posicion','ASC');
        if(!$todas){
            $query->andWhere('t.isActive=:active')
                  ->setParameter('active', true);
        }

        return $query->getQuery();
    }
    
    public function getTracksPorDiscosPorActivas($disco,$todas=false){
        $query=$this->getQueryTracksPorDiscoActivas($disco,$todas);
        return $query->getResult();
    }
    
    public function getRegistroUpOrDown(\Richpolis\FrontendBundle\Entity\Tracks $track,$up=true){
        // $up = true, $up = false is down
        if($up){
            //up
            $query=$this->createQueryBuilder('p')
                    ->where('p.posicion<:posicion')
                    ->setParameter('posicion', $track->getPosicion())
                    ->andWhere('p.disco=:disco')
                    ->setParameter('disco',$track->getDisco()->getId())
                    ->orderBy('p.posicion', 'DESC');
        }else{
            //down
            $query=$this->createQueryBuilder('p')
                    ->where('p.posicion>:posicion')
                    ->setParameter('posicion', $track->getPosicion())
                    ->andWhere('p.disco=:disco')
                    ->setParameter('disco',$track->getDisco()->getId())
                    ->orderBy('p.posicion', 'ASC');
        }
        
        return $query->getQuery()->setMaxResults(1)->getOneOrNullResult();
    }
}
